linters:
  enable:
    - gofmt
    - gocyclo
    - revive
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - exportloopref
    - dupl
    - decorder
    - errorlint
    - nilerr
    - nilnil
issues:
  exclude-use-default: false